# frozen_string_literal: true

# Gemfile for a traditional Rails app with RapiTapir
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

# Rails framework
gem 'rails', '~> 8.0.0'

# Database
gem 'sqlite3', '~> 1.4'

# Web server
gem 'puma', '~> 6.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# RapiTapir for API definitions
# In a real app, you'd add this to your Gemfile:
# gem 'rapitapir', '~> 1.0'

# For this example, we'll use a local path
gem 'rapitapir', path: '../../../'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
